package io.kontour.ui.docs

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import io.kontour.ui.foundation.HorizontalDivider
import io.kontour.ui.foundation.Text
import io.kontour.ui.theme.Theme

/**
 * Every parameter of everything this page documents.
 *
 * Placed under the prose rather than over it because it answers the second
 * question. The first is "what is this and what does it look like", which the
 * demo and the paragraphs answer; this is "and what do I pass", which is asked
 * with the answer to the first already in hand.
 *
 * The content comes from [apiBySymbol], generated by `:ui-docs:generateApiTables`
 * out of `:ui`'s own source. Nothing here is written by hand and nothing here
 * can drift.
 */
@Composable
fun ApiSection(page: DocPage, modifier: Modifier = Modifier) {
    val entries = remember(page.slug) {
        page.symbols
            .flatMap { apiBySymbol[it].orEmpty() }
            // Two symbols on one page can name the same declaration —
            // `Modifier.fadingEdges` is reachable as itself and as a member of
            // nothing else — and an overload must survive, so identity is the
            // owner, the name and the parameter names together.
            .distinctBy { Triple(it.owner, it.name, it.parameters.map(ApiParameter::name)) }
    }
    if (entries.isEmpty()) return

    Column(modifier, verticalArrangement = Arrangement.spacedBy(Theme.spacing.md)) {
        Text(
            text = "API",
            style = Theme.typography.headlineSmall,
            modifier = Modifier.padding(top = Theme.spacing.lg),
        )
        entries.forEach { entry -> EntryBlock(entry) }
    }
}

@Composable
private fun EntryBlock(entry: ApiEntry) {
    Column(verticalArrangement = Arrangement.spacedBy(Theme.spacing.xs)) {
        Row(
            horizontalArrangement = Arrangement.spacedBy(Theme.spacing.sm),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text(
                text = listOfNotNull(entry.owner, entry.name).joinToString("."),
                style = Theme.typography.titleSmall.copy(fontFamily = FontFamily.Monospace),
            )
            if (entry.isComposable) {
                Text(
                    text = "@Composable",
                    style = Theme.typography.monoLabel,
                    color = Theme.colors.accent.solid,
                )
            }
        }

        if (entry.parameters.isEmpty()) {
            Text(
                text = "No parameters.",
                style = Theme.typography.bodySmall,
                color = Theme.colors.contentMuted,
            )
        } else {
            // The same question `DocTable` asks, for the same reason: below the
            // point where three columns hold a phrase, a table read sideways on
            // a phone is worse than a list, so it becomes one.
            BoxWithConstraints(Modifier.fillMaxWidth()) {
                if (maxWidth >= TableWidth) WideTable(entry) else StackedList(entry)
            }
        }

        entry.enums.mapNotNull { apiEnums[it] }.forEach { enum ->
            Text(
                text = "${enum.name}: ${enum.values.joinToString(", ")}",
                style = Theme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace),
                color = Theme.colors.contentMuted,
            )
        }
    }
}

/**
 * Below this the three columns cannot hold a phrase.
 *
 * `@Composable RowContentScope.() -> Unit` is 38 characters and is a perfectly
 * ordinary type here, so the type column alone wants most of a phone's width.
 */
private val TableWidth = 560.dp

@Composable
private fun WideTable(entry: ApiEntry) {
    Column(
        Modifier
            .fillMaxWidth()
            .background(Theme.colors.surfaceSunken, Theme.shapes.small)
            .padding(Theme.spacing.sm),
        verticalArrangement = Arrangement.spacedBy(Theme.spacing.xxs),
    ) {
        entry.parameters.forEachIndexed { index, parameter ->
            if (index > 0) HorizontalDivider()
            Row(
                Modifier.fillMaxWidth().padding(vertical = Theme.spacing.xxs),
                horizontalArrangement = Arrangement.spacedBy(Theme.spacing.sm),
                verticalAlignment = Alignment.Top,
            ) {
                Box(Modifier.weight(NameWeight)) { Mono(parameter.name, FontWeight.SemiBold) }
                Box(Modifier.weight(TypeWeight)) { Mono(parameter.type) }
                Box(Modifier.weight(DefaultWeight)) { Default(parameter) }
            }
        }
    }
}

/**
 * The same rows, stacked, for a narrow window.
 *
 * Not a horizontally scrolling table — a parameter list is read top to bottom
 * looking for one name, and a reader who has to scroll sideways to find out
 * whether it is required will not.
 */
@Composable
private fun StackedList(entry: ApiEntry) {
    Column(
        Modifier
            .fillMaxWidth()
            .background(Theme.colors.surfaceSunken, Theme.shapes.small)
            .padding(Theme.spacing.sm),
        verticalArrangement = Arrangement.spacedBy(Theme.spacing.xs),
    ) {
        entry.parameters.forEachIndexed { index, parameter ->
            if (index > 0) HorizontalDivider()
            Column(
                Modifier.fillMaxWidth().padding(vertical = Theme.spacing.xxs),
                verticalArrangement = Arrangement.spacedBy(Theme.spacing.xxs),
            ) {
                Mono(parameter.name, FontWeight.SemiBold)
                Mono(parameter.type)
                Default(parameter)
            }
        }
    }
}

@Composable
private fun Mono(text: String, weight: FontWeight = FontWeight.Normal) {
    Text(
        text = text,
        style = Theme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace, fontWeight = weight),
        color = Theme.colors.content,
    )
}

/**
 * What happens if it is left out.
 *
 * "required" rather than an empty cell: an empty cell is the same picture as a
 * default nobody bothered to write down, and the difference is the only thing
 * on this row a caller has to act on.
 */
@Composable
private fun Default(parameter: ApiParameter) {
    Text(
        text = parameter.default?.let { "= $it" } ?: "required",
        style = Theme.typography.bodySmall.copy(
            fontFamily = if (parameter.required) FontFamily.Default else FontFamily.Monospace,
        ),
        color = if (parameter.required) Theme.colors.contentMuted else Theme.colors.content,
    )
}

private const val NameWeight = 1f
private const val TypeWeight = 1.7f
private const val DefaultWeight = 1.3f
