package io.kontour.ui.docs

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.BoxWithConstraints
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.input.pointer.PointerIcon
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import io.kontour.ui.components.display.Tag
import io.kontour.ui.components.display.TagTone
import io.kontour.ui.foundation.HorizontalDivider
import io.kontour.ui.foundation.Text
import io.kontour.ui.input.pointerCursor
import io.kontour.ui.theme.Theme

/**
 * Every parameter of everything this page documents.
 *
 * Placed under the prose rather than over it because it answers the second
 * question. The first is "what is this and what does it look like", which the
 * demo and the paragraphs answer; this is "and what do I pass", which is asked
 * with the answer to the first already in hand.
 *
 * The content comes from [apiBySymbol], generated by `:ui-docs:generateApiTables`
 * out of `:ui`'s own source. Nothing here is written by hand and nothing here
 * can drift.
 */
@Composable
fun ApiSection(page: DocPage, modifier: Modifier = Modifier) {
    val entries = remember(page.slug) {
        page.symbols
            .flatMap { apiFor(it) }
            // Two symbols on one page can name the same declaration —
            // `Modifier.fadingEdges` is reachable as itself and as a member of
            // nothing else — and an overload must survive, so identity is the
            // owner, the name and the parameter names together.
            .distinctBy { Triple(it.owner, it.name, it.parameters.map(ApiParameter::name)) }
    }
    if (entries.isEmpty()) return

    Column(modifier, verticalArrangement = Arrangement.spacedBy(Theme.spacing.md)) {
        Text(
            text = "API",
            style = Theme.typography.headlineSmall,
            modifier = Modifier.padding(top = Theme.spacing.lg),
        )
        entries.forEach { entry -> EntryBlock(entry) }
    }
}

@Composable
private fun EntryBlock(entry: ApiEntry) {
    Column(verticalArrangement = Arrangement.spacedBy(Theme.spacing.xs)) {
        Row(
            horizontalArrangement = Arrangement.spacedBy(Theme.spacing.sm),
            verticalAlignment = Alignment.CenterVertically,
        ) {
            Text(
                text = listOfNotNull(entry.owner, entry.name).joinToString("."),
                style = Theme.typography.titleSmall.copy(fontFamily = FontFamily.Monospace),
            )
            // A `Tag`, not accent-coloured text. It marks a *kind* of thing,
            // which is what a tag is for, and the page beside it documents
            // `Tag` — a site that draws its own version of a component it is
            // explaining is arguing against itself.
            if (entry.isComposable) {
                Tag(tone = TagTone.Accent) { +"@Composable" }
            }
            // Beside the entry rather than at the top of the page, which is
            // what it replaces. A page documents up to a dozen declarations and
            // one button at the top could only ever point at the first of them,
            // so on a builder page it was a link to the component from a table
            // about its scope's members.
            //
            // Only where there is somewhere to go. A symbol with no published
            // page, or one whose simple name is ambiguous, gets no link at all
            // rather than a link to the reference's front door: a link that
            // does not go where it says is worse than no link, and the reader
            // has no way to tell the two apart until they have followed it.
            entry.reference?.let { url ->
                Text(
                    text = "reference",
                    style = Theme.typography.monoLabel,
                    colour = Theme.colours.accent.solid,
                    modifier = Modifier
                        .pointerCursor(PointerIcon.Hand)
                        .clickable { openExternal(url) },
                )
            }
        }

        if (entry.parameters.isEmpty()) {
            Text(
                text = "No parameters.",
                style = Theme.typography.bodySmall,
                colour = Theme.colours.contentMuted,
            )
        } else {
            // The same question `DocTable` asks, for the same reason: below the
            // point where three columns hold a phrase, a table read sideways on
            // a phone is worse than a list, so it becomes one.
            BoxWithConstraints(Modifier.fillMaxWidth()) {
                if (maxWidth >= TableWidth) WideTable(entry) else StackedList(entry)
            }
        }

        entry.enums.mapNotNull { apiEnums[it] }.forEach { enum ->
            Text(
                text = "${enum.name}: ${enum.values.joinToString(", ")}",
                style = Theme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace),
                colour = Theme.colours.contentMuted,
            )
        }
    }
}

/**
 * Below this the three columns cannot hold a phrase.
 *
 * `@Composable RowContentScope.() -> Unit` is 38 characters and is a perfectly
 * ordinary type here, so the type column alone wants most of a phone's width.
 */
private val TableWidth = 560.dp

@Composable
private fun WideTable(entry: ApiEntry) {
    Column(
        Modifier
            .fillMaxWidth()
            .background(Theme.colours.surfaceSunken, Theme.shapes.small)
            .padding(Theme.spacing.sm),
        verticalArrangement = Arrangement.spacedBy(Theme.spacing.xxs),
    ) {
        entry.parameters.forEachIndexed { index, parameter ->
            if (index > 0) HorizontalDivider()
            Row(
                Modifier.fillMaxWidth().padding(vertical = Theme.spacing.xxs),
                horizontalArrangement = Arrangement.spacedBy(Theme.spacing.sm),
                verticalAlignment = Alignment.Top,
            ) {
                Box(Modifier.weight(NameWeight)) { Mono(parameter.name, FontWeight.SemiBold) }
                Box(Modifier.weight(TypeWeight)) { Mono(parameter.type) }
                Box(Modifier.weight(DefaultWeight)) { Default(parameter) }
            }
            Description(parameter)
        }
    }
}

/**
 * What the parameter is for, under the row rather than beside it.
 *
 * A fourth column would have to come out of the three that are there, and the
 * type column is already the tight one — `@Composable RowContentScope.() -> Unit`
 * is an ordinary type here. Under the row it gets the whole width, which is
 * what a sentence wants, and it costs the rows nothing on the nine in ten
 * parameters that have nothing to say.
 *
 * Nothing at all when there is no description, rather than an empty cell. An
 * empty cell is a claim that something is missing; a row that is simply three
 * columns wide is not.
 */
@Composable
private fun Description(parameter: ApiParameter) {
    val description = parameter.description ?: return
    Text(
        text = description,
        style = Theme.typography.bodySmall,
        colour = Theme.colours.contentMuted,
        modifier = Modifier.fillMaxWidth().padding(bottom = 2.dp),
    )
}

/**
 * The same rows, stacked, for a narrow window.
 *
 * Not a horizontally scrolling table — a parameter list is read top to bottom
 * looking for one name, and a reader who has to scroll sideways to find out
 * whether it is required will not.
 */
@Composable
private fun StackedList(entry: ApiEntry) {
    Column(
        Modifier
            .fillMaxWidth()
            .background(Theme.colours.surfaceSunken, Theme.shapes.small)
            .padding(Theme.spacing.sm),
        verticalArrangement = Arrangement.spacedBy(Theme.spacing.xs),
    ) {
        entry.parameters.forEachIndexed { index, parameter ->
            if (index > 0) HorizontalDivider()
            Column(
                Modifier.fillMaxWidth().padding(vertical = Theme.spacing.xxs),
                verticalArrangement = Arrangement.spacedBy(Theme.spacing.xxs),
            ) {
                Mono(parameter.name, FontWeight.SemiBold)
                Mono(parameter.type)
                Default(parameter)
                Description(parameter)
            }
        }
    }
}

@Composable
private fun Mono(text: String, weight: FontWeight = FontWeight.Normal) {
    Text(
        text = text,
        style = Theme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace, fontWeight = weight),
        colour = Theme.colours.content,
    )
}

/**
 * What happens if it is left out.
 *
 * "required" rather than an empty cell: an empty cell is the same picture as a
 * default nobody bothered to write down, and the difference is the only thing
 * on this row a caller has to act on.
 */
@Composable
private fun Default(parameter: ApiParameter) {
    Text(
        text = parameter.default?.let { "= $it" } ?: "required",
        style = Theme.typography.bodySmall.copy(
            fontFamily = if (parameter.required) FontFamily.Default else FontFamily.Monospace,
        ),
        colour = if (parameter.required) Theme.colours.contentMuted else Theme.colours.content,
    )
}

private const val NameWeight = 1f
private const val TypeWeight = 1.7f
private const val DefaultWeight = 1.3f
