package io.kontour.ui.platform

// GENERATED by docs/pull-device-corners.py — do not edit by hand.
//
//   python3 docs/pull-device-corners.py --pull    # refresh docs/device-corners.json
//   python3 docs/pull-device-corners.py --write   # regenerate this file
//
// 27 devices, from LineageOS device trees. Every one of them is a device the
// platform cannot be asked: `RoundedCorner` arrived in API 31 and these overlays
// are overwhelmingly older hardware, so this table and the platform cover
// disjoint sets rather than disagreeing about the same one.

/** `codename|topDp|bottomDp` records, `;`-separated and sorted by codename. */
internal const val DeviceRadiusTable: String =
    "Spacewar|43|43;akita|51|51;beckham|15|15;bluejay|19|19;borneo|37|37;channel|35|35;chiron|20|20;cmi|44|44;devon|38|38;evert|10|10;grus|43|50;hawao|40|40;lake|44|44;laurel_sprout|38|38;lynx|19|19;mata|5|5;monet|50|45;perseus|34|34;polaris|20|20;renoir|50|50;rhode|38|38;taimen|26|26;tangorpro|19|18;thyme|44|44;umi|44|44;vela|38|42;violet|41|41"
